# Generated by Django 2.2.4 on 2019-08-22 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0003_auto_20190822_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goldmine',
            fields=[
                ('building_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='engine.Building')),
                ('new_thing', models.IntegerField(default=200)),
            ],
            bases=('engine.building',),
        ),
    ]
