# Generated by Django 2.2.4 on 2019-08-22 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0004_goldmine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building',
            old_name='cost',
            new_name='cost_gold',
        ),
        migrations.RemoveField(
            model_name='goldmine',
            name='new_thing',
        ),
        migrations.AddField(
            model_name='building',
            name='cost_lumber',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='building',
            name='cost_stone',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='building',
            name='score_addition',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='goldmine',
            name='gold_per_hour',
            field=models.IntegerField(default=0),
        ),
    ]
