# Generated by Django 2.2.4 on 2019-08-23 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0005_auto_20190822_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='gold_accrual',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='player',
            name='lumber_accrual',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='player',
            name='stone_accrual',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='player',
            name='gold',
            field=models.FloatField(default=200),
        ),
        migrations.AlterField(
            model_name='player',
            name='lumber',
            field=models.FloatField(default=200),
        ),
        migrations.AlterField(
            model_name='player',
            name='stone',
            field=models.FloatField(default=200),
        ),
    ]
